name: Cucumber Allure tests CI

on:
  workflow_call:
    inputs:
      BROWSER:
        type: string

  workflow_dispatch:
    inputs:
      BROWSER:
        type: choice
        required: true
        description: Select supported browser
        options:
          - chrome
          - firefox
          - edge
        default: chrome

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start Selenoid Server
        uses: Xotabu4/selenoid-github-action@v2
        with:
          selenoid-start-arguments: |
            --browsers-json "./browsers.json"
        id: start-selenoid
        continue-on-error: false

      - name: Check Selenoid has been started
        run: |
          response=$(curl --head --fail http://localhost:4444/status 2>&1)
          if [ $? -eq 0 ]; then
            echo "Selenoid is available on localhost:4444"
            echo "Response: $response"
          else
            echo "Selenoid is not available on localhost:4444"
          fi

      - name: Build and Test with Gradle
        if: always()
        run: |
          ./gradlew clean test -Dselenide.headless=false -Dselenide.browser=inputs.BROWSER
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://mrc81.github.io/QAtest_Cucumber/${{ github.run_number }}
